include(":platform-database")
include(":common")
include(":platform-permission")
include(":platform-image")
include(":platform-storage")
include(":platform-router")
include(":platform-network")
include(":platform-log")
include(":platform-startup")
include(":app")
rootProject.name = "Componentization Architecture Sample"